spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/yuelenghan/soa-demo.git
          searchPaths: spring-cloud-4.0/config-repo
          username: username
          password: password
  rabbitmq:
    host: 10.47.160.238
    port: 5673
    username: guest
    password: guest
  profiles:
    active: @activatedProperties@

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

