spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      server:
        git:
          uri: http://10.47.160.210:18080/soa/config-repo.git
          username: lihe
          password: 123456
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: 10.47.160.238
    port: 5673
    username: guest
    password: guest
  profiles:
    active: @activatedProperties@

server:
  port: 8888

endpoints:
  restart:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

