spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      server:
        git:
          uri: http://10.47.160.210:18080/soa/config-repo.git
          username: username
          password: password

server:
  port: 8888

endpoints:
  restart:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8000/eureka/

