spring:
  application:
    name: @project.artifactId@

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8000/eureka/

zuul:
  routes:
    add-service-demo:
      path: /add-service/**
      serviceId: add-service-demo